---
title: "Dataset: Precios de productos de supermercados"
author: "Andrés Baamonde Lozano"
author: "David"
date: "12 de marzo de 2021"
header-includes:
  - \usepackage[spanish]{babel}
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1. Contexto. Explicar en qué contexto se ha recolectado la información. Explique por qué el sitio web elegido proporciona dicha información.

> La práctica trata sobre web scraping y se ha enfocado en el ámbito de la alimentación, en concreto, buscamos recolectar datos relativos a el precio y tipo de los productos de diferentes supermercados. Con estos datos para así, tener un histórico de los precios de sus productos y comprarlos con otros supermercados online.

2. Definir un título para el dataset. Elegir un título que sea descriptivo.

3. Descripción del dataset. Desarrollar una descripción breve del conjunto de datos que se ha extraído (es necesario que esta descripción tenga sentido con el título elegido).

4. Representación  gráfica.  Presentar  esquema  o  diagrama  que  identifique  el dataset visualmente y el proyecto elegido

5. Contenido. Explicar los campos que incluye el dataset,  el periodo de tiempo de los datos y cómo se ha recogido.

6. Agradecimientos. Presentar al propietario del conjunto de datos. Es necesario incluir  citas  de  análisis  anteriores  o,  en  caso  de  no  haberlas,  justificar  esta búsqueda con análisis similares.

7. Inspiración.  Explique  por  qué  es  interesante  este  conjunto  de  datos  y  qué preguntas  se  pretenden  responder.  Es  necesario  comparar  con  los  análisis anteriores presentados en el apartado 6.

8. Licencia. Seleccione una de estas licencias para su dataset y explique el motivo de su selección:
    - Released Under CC0: Public Domain License
    - Released Under CC BY-NC-SA 4.0 License
    - Released Under CC BY-SA 4.0 License
    - Database released under Open Database License, individual contents under Database Contents License○Other (specified above)
    - Unknown License

9. Código. Adjuntar el código con el que se ha generado el dataset, preferiblemente en Python o, alternativamente, en R.10.Dataset. Publicación del dataset en formato CSV en Zenodo (obtención del DOI) con una breve descripción.